

services:
  python_embedder:
    build:
      context: ./Python_Embedder
    container_name: python_embedder
    volumes:
      - ./Python_Embedder:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - PYTHON_API_HOST=0.0.0.0
    ports:
      - "8001:8001"
    depends_on:
      - redis

  rust_lsh:
    build:
      context: ./Rust_LSH
    container_name: rust_lsh
    volumes:
      - ./Rust_LSH:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - RUST_API_HOST=0.0.0.0
    ports:
      - "8002:8002"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8030:8030"
    depends_on:
      - python_embedder
      - rust_lsh
